export const homeVillage = {
  buildings: {
    defense: [
      'Cannon',
      'Archer Tower',
      'Mortar',
      'Air Defense',
      'Wizard Tower',
      'Air Sweeper',
      'Hidden Tesla',
      'Bomb Tower',
      'X-Bow',
      'Inferno Tower',
      'Eagle Artillery',
      'Scattershot',
      "Builder's Hut",
      'Bomb',
      'Spring Trap',
      'Air Bomb',
      'Giant Bomb',
      'Seeking Air Mine',
      'Skeleton Trap',
      'Tornado Trap',
    ],
    army: [
      'Army Camp',
      'Barracks',
      'Dark Barracks',
      'Laboratory',
      'Spell Factory',
      'Dark Spell Factory',
      'Workshop',
      'Pet House',
    ],
    resource: [
      'Gold Mine',
      'Elixir Collector',
      'Dark Elixir Drill',
      'Gold Storage',
      'Elixir Storage',
      'Dark Elixir Storage',
      'Clan Castle',
    ],
  },
}
